In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
s = pd.Series([1,2,3,4,5,6,np.nan,7,8,9,10])

s

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      6.0
6      NaN
7      7.0
8      8.0
9      9.0
10    10.0
dtype: float64

In [8]:
# dataframe 1 month & virtual 4 Colums

In [9]:
d = pd.date_range('20250801',periods=30)
d

DatetimeIndex(['2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04',
               '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08',
               '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12',
               '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
               '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20',
               '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24',
               '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
               '2025-08-29', '2025-08-30'],
              dtype='datetime64[ns]', freq='D')

In [10]:
data = pd.DataFrame(np.random.randn(30,4),index=d,columns=['A','B','C','D'])
data

                   A         B         C         D
2025-08-01 -1.212761  1.080721  0.311963 -0.348280
2025-08-02  0.053813 -0.835633 -0.161789 -1.860461
2025-08-03  1.689782  0.724054  1.014526  1.565694
2025-08-04  0.918388 -0.658264  0.303758  0.535784
2025-08-05  0.619850 -1.406153  0.011185 -1.296437
2025-08-06 -0.351850 -0.725838  0.343797  0.497818
2025-08-07 -0.169854 -0.084109  1.251918  0.093664
2025-08-08  0.161304 -0.689956  0.137249 -0.055091
2025-08-09 -1.009343 -1.313176 -0.800774  0.656826
2025-08-10 -1.429914  0.451743  0.949666  0.805243
2025-08-11 -0.858996 -0.768245 -1.130831 -1.781678
2025-08-12 -0.294527  1.045393 -0.781700  0.954195
2025-08-13 -0.732824 -0.766099 -0.107830 -1.011487
2025-08-14 -0.547890  0.236770  1.749013  0.782530
2025-08-15  1.727113 -0.161110 -0.260635 -0.799964
2025-08-16  0.818649 -0.016230  1.521106 -0.069062
2025-08-17  0.096311 -1.159595  0.415358  0.229789
2025-08-18 -0.661640  0.405236  0.922242 -0.573162
2025-08-19 -1.322004  0.149595  1.630308  0.273328
2025-08-20  0.301162  0.715864  1.719004  0.390361
2025-08-21 -2.423332 -0.817194  0.696821 -0.869413
2025-08-22 -1.221617  0.053723  0.921002  0.610930
2025-08-23  0.586823  0.029505  1.043304  1.329177
2025-08-24  2.005666 -1.595510  0.645062 -0.121591
2025-08-25 -0.085859  1.646604 -0.406878  0.832719
2025-08-26  2.005011  0.039041  0.030744  1.153147
2025-08-27  0.516876 -1.326508  0.507290  0.577844
2025-08-28  0.609293 -0.535362  1.283540  0.299192
2025-08-29 -1.228000 -0.637796  1.468366 -0.548603
2025-08-30 -0.040971 -0.068865  0.258999 -1.229882

In [11]:
data.head()

                   A         B         C         D
2025-08-01 -1.212761  1.080721  0.311963 -0.348280
2025-08-02  0.053813 -0.835633 -0.161789 -1.860461
2025-08-03  1.689782  0.724054  1.014526  1.565694
2025-08-04  0.918388 -0.658264  0.303758  0.535784
2025-08-05  0.619850 -1.406153  0.011185 -1.296437

In [12]:
data.tail()

                   A         B         C         D
2025-08-26  2.005011  0.039041  0.030744  1.153147
2025-08-27  0.516876 -1.326508  0.507290  0.577844
2025-08-28  0.609293 -0.535362  1.283540  0.299192
2025-08-29 -1.228000 -0.637796  1.468366 -0.548603
2025-08-30 -0.040971 -0.068865  0.258999 -1.229882

In [13]:
data.index

DatetimeIndex(['2025-08-01', '2025-08-02', '2025-08-03', '2025-08-04',
               '2025-08-05', '2025-08-06', '2025-08-07', '2025-08-08',
               '2025-08-09', '2025-08-10', '2025-08-11', '2025-08-12',
               '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
               '2025-08-17', '2025-08-18', '2025-08-19', '2025-08-20',
               '2025-08-21', '2025-08-22', '2025-08-23', '2025-08-24',
               '2025-08-25', '2025-08-26', '2025-08-27', '2025-08-28',
               '2025-08-29', '2025-08-30'],
              dtype='datetime64[ns]', freq='D')

In [14]:
data.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [15]:
data.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [16]:
data.shape

(30, 4)

In [17]:
data.to_numpy()

array([[-1.2127608 ,  1.08072148,  0.31196272, -0.34828042],
       [ 0.05381274, -0.83563312, -0.16178938, -1.86046118],
       [ 1.68978186,  0.72405384,  1.01452642,  1.56569376],
       [ 0.91838845, -0.65826385,  0.3037583 ,  0.53578431],
       [ 0.61985014, -1.40615252,  0.01118492, -1.29643678],
       [-0.35185012, -0.72583765,  0.34379717,  0.49781826],
       [-0.1698542 , -0.08410883,  1.2519182 ,  0.0936636 ],
       [ 0.16130417, -0.68995563,  0.13724868, -0.05509059],
       [-1.0093434 , -1.31317647, -0.80077407,  0.65682612],
       [-1.42991414,  0.45174321,  0.94966644,  0.80524261],
       [-0.85899648, -0.76824469, -1.1308312 , -1.78167775],
       [-0.29452707,  1.04539322, -0.78170044,  0.95419532],
       [-0.73282351, -0.76609942, -0.10782951, -1.01148731],
       [-0.54788987,  0.23676954,  1.74901302,  0.78253019],
       [ 1.72711347, -0.16110967, -0.26063469, -0.79996393],
       [ 0.81864855, -0.01623015,  1.52110597, -0.06906246],
       [ 0.09631059, -1.15959494,  0.41535779,  0.22978896],
       [-0.66164003,  0.40523585,  0.92224164, -0.57316226],
       [-1.32200428,  0.14959515,  1.6303084 ,  0.27332811],
       [ 0.3011621 ,  0.71586358,  1.7190038 ,  0.39036145],
       [-2.42333234, -0.81719397,  0.69682143, -0.86941319],
       [-1.22161719,  0.05372265,  0.92100236,  0.61093009],
       [ 0.58682312,  0.02950451,  1.04330441,  1.32917742],
       [ 2.00566576, -1.59550992,  0.64506232, -0.12159143],
       [-0.08585899,  1.64660443, -0.40687805,  0.83271864],
       [ 2.00501067,  0.0390408 ,  0.03074437,  1.15314731],
       [ 0.51687625, -1.32650766,  0.5072902 ,  0.57784441],
       [ 0.60929346, -0.53536248,  1.28353978,  0.29919159],
       [-1.22799964, -0.63779635,  1.4683657 , -0.54860349],
       [-0.04097118, -0.06886534,  0.2589985 , -1.22988181]])

In [18]:
data.describe()

               A          B          C          D
count  30.000000  30.000000  30.000000  30.000000
mean   -0.049378  -0.232913   0.516193   0.034104
std     1.086492   0.807205   0.779256   0.899245
min    -2.423332  -1.595510  -1.130831  -1.860461
25%    -0.827453  -0.767708   0.016075  -0.567023
50%    -0.063415  -0.122609   0.461324   0.251559
75%     0.603676   0.214976   1.036110   0.645352
max     2.005666   1.646604   1.749013   1.565694

In [19]:
data.sort_values(by=['C','A'],ascending=True)

                   A         B         C         D
2025-08-11 -0.858996 -0.768245 -1.130831 -1.781678
2025-08-09 -1.009343 -1.313176 -0.800774  0.656826
2025-08-12 -0.294527  1.045393 -0.781700  0.954195
2025-08-25 -0.085859  1.646604 -0.406878  0.832719
2025-08-15  1.727113 -0.161110 -0.260635 -0.799964
2025-08-02  0.053813 -0.835633 -0.161789 -1.860461
2025-08-13 -0.732824 -0.766099 -0.107830 -1.011487
2025-08-05  0.619850 -1.406153  0.011185 -1.296437
2025-08-26  2.005011  0.039041  0.030744  1.153147
2025-08-08  0.161304 -0.689956  0.137249 -0.055091
2025-08-30 -0.040971 -0.068865  0.258999 -1.229882
2025-08-04  0.918388 -0.658264  0.303758  0.535784
2025-08-01 -1.212761  1.080721  0.311963 -0.348280
2025-08-06 -0.351850 -0.725838  0.343797  0.497818
2025-08-17  0.096311 -1.159595  0.415358  0.229789
2025-08-27  0.516876 -1.326508  0.507290  0.577844
2025-08-24  2.005666 -1.595510  0.645062 -0.121591
2025-08-21 -2.423332 -0.817194  0.696821 -0.869413
2025-08-22 -1.221617  0.053723  0.921002  0.610930
2025-08-18 -0.661640  0.405236  0.922242 -0.573162
2025-08-10 -1.429914  0.451743  0.949666  0.805243
2025-08-03  1.689782  0.724054  1.014526  1.565694
2025-08-23  0.586823  0.029505  1.043304  1.329177
2025-08-07 -0.169854 -0.084109  1.251918  0.093664
2025-08-28  0.609293 -0.535362  1.283540  0.299192
2025-08-29 -1.228000 -0.637796  1.468366 -0.548603
2025-08-16  0.818649 -0.016230  1.521106 -0.069062
2025-08-19 -1.322004  0.149595  1.630308  0.273328
2025-08-20  0.301162  0.715864  1.719004  0.390361
2025-08-14 -0.547890  0.236770  1.749013  0.782530

In [20]:

data

                   A         B         C         D
2025-08-01 -1.212761  1.080721  0.311963 -0.348280
2025-08-02  0.053813 -0.835633 -0.161789 -1.860461
2025-08-03  1.689782  0.724054  1.014526  1.565694
2025-08-04  0.918388 -0.658264  0.303758  0.535784
2025-08-05  0.619850 -1.406153  0.011185 -1.296437
2025-08-06 -0.351850 -0.725838  0.343797  0.497818
2025-08-07 -0.169854 -0.084109  1.251918  0.093664
2025-08-08  0.161304 -0.689956  0.137249 -0.055091
2025-08-09 -1.009343 -1.313176 -0.800774  0.656826
2025-08-10 -1.429914  0.451743  0.949666  0.805243
2025-08-11 -0.858996 -0.768245 -1.130831 -1.781678
2025-08-12 -0.294527  1.045393 -0.781700  0.954195
2025-08-13 -0.732824 -0.766099 -0.107830 -1.011487
2025-08-14 -0.547890  0.236770  1.749013  0.782530
2025-08-15  1.727113 -0.161110 -0.260635 -0.799964
2025-08-16  0.818649 -0.016230  1.521106 -0.069062
2025-08-17  0.096311 -1.159595  0.415358  0.229789
2025-08-18 -0.661640  0.405236  0.922242 -0.573162
2025-08-19 -1.322004  0.149595  1.630308  0.273328
2025-08-20  0.301162  0.715864  1.719004  0.390361
2025-08-21 -2.423332 -0.817194  0.696821 -0.869413
2025-08-22 -1.221617  0.053723  0.921002  0.610930
2025-08-23  0.586823  0.029505  1.043304  1.329177
2025-08-24  2.005666 -1.595510  0.645062 -0.121591
2025-08-25 -0.085859  1.646604 -0.406878  0.832719
2025-08-26  2.005011  0.039041  0.030744  1.153147
2025-08-27  0.516876 -1.326508  0.507290  0.577844
2025-08-28  0.609293 -0.535362  1.283540  0.299192
2025-08-29 -1.228000 -0.637796  1.468366 -0.548603
2025-08-30 -0.040971 -0.068865  0.258999 -1.229882

In [ ]:
data.loc['20250801':'20250810',['A','B'],]

                   A         B
2025-08-01 -1.212761  1.080721
2025-08-02  0.053813 -0.835633
2025-08-03  1.689782  0.724054
2025-08-04  0.918388 -0.658264
2025-08-05  0.619850 -1.406153
2025-08-06 -0.351850 -0.725838
2025-08-07 -0.169854 -0.084109
2025-08-08  0.161304 -0.689956
2025-08-09 -1.009343 -1.313176
2025-08-10 -1.429914  0.451743

In [24]:
data.sort_values(by='A',ascending=False)

                   A         B         C         D
2025-08-24  2.005666 -1.595510  0.645062 -0.121591
2025-08-26  2.005011  0.039041  0.030744  1.153147
2025-08-15  1.727113 -0.161110 -0.260635 -0.799964
2025-08-03  1.689782  0.724054  1.014526  1.565694
2025-08-04  0.918388 -0.658264  0.303758  0.535784
2025-08-16  0.818649 -0.016230  1.521106 -0.069062
2025-08-05  0.619850 -1.406153  0.011185 -1.296437
2025-08-28  0.609293 -0.535362  1.283540  0.299192
2025-08-23  0.586823  0.029505  1.043304  1.329177
2025-08-27  0.516876 -1.326508  0.507290  0.577844
2025-08-20  0.301162  0.715864  1.719004  0.390361
2025-08-08  0.161304 -0.689956  0.137249 -0.055091
2025-08-17  0.096311 -1.159595  0.415358  0.229789
2025-08-02  0.053813 -0.835633 -0.161789 -1.860461
2025-08-30 -0.040971 -0.068865  0.258999 -1.229882
2025-08-25 -0.085859  1.646604 -0.406878  0.832719
2025-08-07 -0.169854 -0.084109  1.251918  0.093664
2025-08-12 -0.294527  1.045393 -0.781700  0.954195
2025-08-06 -0.351850 -0.725838  0.343797  0.497818
2025-08-14 -0.547890  0.236770  1.749013  0.782530
2025-08-18 -0.661640  0.405236  0.922242 -0.573162
2025-08-13 -0.732824 -0.766099 -0.107830 -1.011487
2025-08-11 -0.858996 -0.768245 -1.130831 -1.781678
2025-08-09 -1.009343 -1.313176 -0.800774  0.656826
2025-08-01 -1.212761  1.080721  0.311963 -0.348280
2025-08-22 -1.221617  0.053723  0.921002  0.610930
2025-08-29 -1.228000 -0.637796  1.468366 -0.548603
2025-08-19 -1.322004  0.149595  1.630308  0.273328
2025-08-10 -1.429914  0.451743  0.949666  0.805243
2025-08-21 -2.423332 -0.817194  0.696821 -0.869413

In [25]:
data.loc['20250801',['A']]

A   -1.212761
Name: 2025-08-01 00:00:00, dtype: float64

In [30]:
data.iloc[5:10,0:2]

                   A         B
2025-08-06 -0.351850 -0.725838
2025-08-07 -0.169854 -0.084109
2025-08-08  0.161304 -0.689956
2025-08-09 -1.009343 -1.313176
2025-08-10 -1.429914  0.451743

In [31]:
data['A'] > 0

2025-08-01    False
2025-08-02     True
2025-08-03     True
2025-08-04     True
2025-08-05     True
2025-08-06    False
2025-08-07    False
2025-08-08     True
2025-08-09    False
2025-08-10    False
2025-08-11    False
2025-08-12    False
2025-08-13    False
2025-08-14    False
2025-08-15     True
2025-08-16     True
2025-08-17     True
2025-08-18    False
2025-08-19    False
2025-08-20     True
2025-08-21    False
2025-08-22    False
2025-08-23     True
2025-08-24     True
2025-08-25    False
2025-08-26     True
2025-08-27     True
2025-08-28     True
2025-08-29    False
2025-08-30    False
Freq: D, Name: A, dtype: bool